INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (1, 'Cielo Azul', 20, 'Sur', 100, 80000, 3, 1, 1);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (2, 'Oasis Tropical', 1, 'Este', 1, 100000, 1, 2, 2);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (3, 'Casa del Mar', 4, 'Norte', 30, 50000, 2, 3, 3);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (4, 'El Faro', 10, 'Sur', 70, 90000, 6, 4, 4);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (5, 'Villa Serena', 30, 'Este', 150, 120000, 15, 5, 5);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (6, 'La Perla del Caribe', 5, 'Oeste', 40, 60000, 4, 6, 6);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (7, 'El Paraíso', 2, 'Norte', 20, 40000, 2, 7, 7);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (8, 'Los Tres Hermanos', 8, 'Este', 60, 70000, 6, 8, 8);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (9, 'La Casa Blanca', 12, 'Sur', 90,250000, 5, 9, 9);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (10, 'Finca El Encanto', 8, 'Oeste', 70, 200000, 2, 10, 10);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (11, 'Hotel La Estancia', 14, 'Norte', 100, 300000, 8, 11, 11);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (12, 'Hacienda San Miguel', 4, 'Este', 60, 150000, 1, 12, 12);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (13, 'Rancho Las Palmas', 2, 'Norte', 30, 80000, 4, 13, 13);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (14, 'Posada Los Amigos', 6, 'Sur', 80, 120000, 3, 14, 14);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (15, 'Posada La Hacienda', 18, 'Este', 120, 350000, 9, 15, 15);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (16, 'Hostal San Pedro', 10, 'Oeste', 90, 180000, 5, 16, 16);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (17, 'El Refugio', 14, 'Norte', 100, 280000, 6, 17, 17);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (18, 'La Cabaña del Bosque', 22, 'Sur', 130, 450000, 12, 18, 18);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR )
VALUES (19, 'Casa de Campo', 6, 'Norte', 80, 60000, 2, 19, 19);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR )
VALUES (20, 'La Quinta del Sol', 8, 'Este', 70, 75000, 1, 20, 20);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR )
VALUES (21, 'Betelgeuse', 10, 'Oeste', 85, 90000, 4, 21, 21);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR )
VALUES (22, 'Alpha Centauri', 2, 'Norte', 30, 50000, 2, 22, 22);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR )
VALUES (23, 'Vega', 4, 'Sur', 40, 35000, 10, 23, 23);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR )
VALUES (24, 'Andromeda', 15, 'Este', 120, 120000, 5, 24, 24);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR )
VALUES (25, 'Proxima Centauri', 1, 'Oeste', 20, 40000, 1, 25, 25);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR )
VALUES (26, 'Cassiopeia', 12, 'Norte', 95, 85000, 2, 26, 26);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR )
VALUES (27, 'Aldebaran', 8, 'Este', 70, 70000, 1, 27, 27);

NSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (28, 'Plutón', 2, 'Norte', 30, 90000, 0, 28, 28);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (29, 'Venus', 8, 'Sur', 60, 110000, 2, 29, 29);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (30, 'Mercurio', 3, 'Este', 35, 95000, 1, 30, 30);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (31, 'Júpiter', 10, 'Norte', 70, 150000, 5, 3, 1);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (32, 'Tierra', 4, 'Este', 40, 100000, 1, 1, 2);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (33, 'Mars', 6, 'Oeste', 50, 130000, 5, 0, 3);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (34, 'Urano', 7, 'Sur', 55, 140000, 2, 1, 4);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (35, 'Hotel Los Pinos', 11, 'Norte', 75, 155000, 3, 2, 5);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (36, 'Finca La Esperanza', 8, 'Este', 75, 85000, 2, 1, 6);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (37, 'Mercurio', 4, 'Centro', 40, 60000, 1, 0, 7);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (38, 'Urano', 6, 'Norte', 60, 70000, 3, 1, 8);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (39, 'El Castillo', 10, 'Sur', 80, 90000, 2, 0, 9);

INSERT INTO A_ALOJAMIENTO(IDALOJAMIENTO, NOMBRE, CAPACIDAD, UBICACION, TAMANO, PRECIONOCHE, OCUPACIONACTUAL, NUMRESERVAS, IDOPERADOR)
VALUES (40, 'Villa La Playa', 18, 'Oeste', 110, 100000, 50, 1, 3);