-- MOSTRAR EL DINERO RECIBIDO POR CADA PROVEEDOR DE ALOJAMIENTO DURANTE EL AÑO ACTUAL Y EL AÑO CORRIDO

SELECT op.IDOPERADOR, COALESCE(SUM(r.COSTOTOTAL), 0) as COSTO_TOTAL_RECIBIDO
FROM A_OPERADOR op
LEFT JOIN A_ALOJAMIENTO al ON op.IDOPERADOR = al.IDOPERADOR
LEFT JOIN A_RESERVA r ON al.IDALOJAMIENTO = r.IDALOJAMIENTO
    AND r.ESTADO = 'Finalizada'
    AND r.FECHAINICIO <= TO_DATE('2023-01-01', 'YYYY-MM-DD')
    AND r.FECHAFINAL <= TO_DATE('2023-04-09', 'YYYY-MM-DD')
GROUP BY op.IDOPERADOR;