-- MOSTRAR EL ÍNDICE DE OCUPACIÓN DE CADA UNA DE LAS OFERTAS DE ALOJAMIENTO REGISTRADAS
SELECT IDALOJAMIENTO, NOMBRE,
       (OCUPACIONACTUAL / CAPACIDAD) * 100 AS INDICE_OCUPACION
FROM A_ALOJAMIENTO;